const products = [
  {
    id: 1,
    name: "Samsung Galaxy S23",
    price: 999,
    quantity: 15,
    category: "Smartfonlar",
    brand: "Samsung",
    description:
      "Yuqori unumli kamera va kuchli protsessor bilan jihozlangan smartfon.",
  },
  {
    id: 2,
    name: "Apple MacBook Air M2",
    price: 1299,
    quantity: 7,
    category: "Noutbuklar",
    brand: "Apple",
    description:
      "Engil va kuchli noutbuk, talaba va professionallar uchun ideal tanlov.",
  },
  {
    id: 3,
    name: 'LG 55" 4K TV',
    price: 750,
    quantity: 10,
    category: "Televizorlar",
    brand: "LG",
    description: "55 dyuymli 4K UHD ekran, aqlli tizim bilan.",
  },
  {
    id: 4,
    name: "Sony WH-1000XM5",
    price: 399,
    quantity: 20,
    category: "Quloqchinlar",
    brand: "Sony",
    description:
      "Dunyoning eng yaxshi shovqinni kamaytiruvchi quloqchinlaridan biri.",
  },
  {
    id: 5,
    name: "Dell XPS 13",
    price: 1199,
    quantity: 5,
    category: "Noutbuklar",
    brand: "Dell",
    description: "Kuchli ishlov berish va yuqori darajadagi dizayn.",
  },
  {
    id: 6,
    name: "Canon EOS R50",
    price: 899,
    quantity: 8,
    category: "Kameralar",
    brand: "Canon",
    description: "Yangi boshlovchilar uchun mukammal mirrorless kamera.",
  },
  {
    id: 7,
    name: "Nike Air Max 270",
    price: 150,
    quantity: 30,
    category: "Poyabzallar",
    brand: "Nike",
    description:
      "Zamonaviy dizayn va qulay yurish uchun mukammal sport poyabzali.",
  },
  {
    id: 8,
    name: "Logitech MX Master 3S",
    price: 99,
    quantity: 25,
    category: "Kompyuter aksessuarlari",
    brand: "Logitech",
    description: "Ergonomik dizayn va yuqori aniqlikdagi sichqoncha.",
  },
  {
    id: 9,
    name: "Xiaomi Air Purifier 4",
    price: 199,
    quantity: 12,
    category: "Uy jihozlari",
    brand: "Xiaomi",
    description:
      "Havoni tozalovchi zamonaviy qurilma, allergiyaga qarshi samarali.",
  },
  {
    id: 10,
    name: "HP LaserJet Pro M404dn",
    price: 249,
    quantity: 6,
    category: "Printerlar",
    brand: "HP",
    description: "Ofis uchun samarali va tez ishlaydigan printer.",
  },
];
